# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4ce3ad22-075a-488f-85b2-068546c22d1d'
  imageRepository: 'amitabhadazzpipelinessampleapp'
  containerRegistry: 'reg1231231.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'reg1231231d6f2-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Microsoft Azure (DebabrataHowleeCAstgTEST): #1210033(53c6e7e5-5529-42ce-9543-f4fa9e6bfc4f)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'kubectl get nodes'

    - upload: manifests
      artifact: manifests



